import type { Vehicle } from "./types"

export const vehiclesData: Vehicle[] = [
  {
    id: "toyota-sienna-1",
    name: "Toyota Sienna",
    category: "minivan",
    images: [
      "/placeholder.svg?width=800&height=600&text=Toyota+Sienna",
      "/placeholder.svg?width=800&height=600&text=Toyota+Sienna+Interior",
      "/placeholder.svg?width=800&height=600&text=Toyota+Sienna+Side",
    ],
    seats: 7,
    engine: "3.5L V6 Petrol",
    pricePerDay: 70,
    description: "Spacious and comfortable minivan, perfect for families.",
    features: ["Automatic Transmission", "Air Conditioning", "Bluetooth", "USB Ports", "Safety Features"],
  },
  {
    id: "chevrolet-suburban-1",
    name: "Chevrolet Suburban",
    category: "suv",
    images: [
      "/placeholder.svg?width=800&height=600&text=Chevrolet+Suburban",
      "/placeholder.svg?width=800&height=600&text=Suburban+Interior",
      "/placeholder.svg?width=800&height=600&text=Suburban+Cargo",
    ],
    seats: 8,
    engine: "5.3L V8 Petrol",
    pricePerDay: 90,
    description: "Large SUV with plenty of room for passengers and cargo.",
    features: ["4WD", "Leather Seats", "Sunroof", "Navigation", "Premium Sound System"],
  },
  {
    id: "honda-crv-1",
    name: "Honda CR-V",
    category: "suv",
    images: [
      "/placeholder.svg?width=800&height=600&text=Honda+CR-V",
      "/placeholder.svg?width=800&height=600&text=CR-V+Dashboard",
      "/placeholder.svg?width=800&height=600&text=CR-V+Exterior",
    ],
    seats: 5,
    engine: "1.5L Turbo Petrol",
    pricePerDay: 60,
    description: "Reliable and fuel-efficient compact SUV.",
    features: ["Backup Camera", "Apple CarPlay", "Android Auto", "Lane Assist", "Collision Warning"],
  },
  {
    id: "kia-sportage-1",
    name: "Kia Sportage",
    category: "suv",
    images: [
      "/placeholder.svg?width=800&height=600&text=Kia+Sportage",
      "/placeholder.svg?width=800&height=600&text=Sportage+Interior",
      "/placeholder.svg?width=800&height=600&text=Sportage+Features",
    ],
    seats: 5,
    engine: "2.4L Petrol",
    pricePerDay: 55,
    description: "Stylish SUV with a comfortable ride.",
    features: ["Panoramic Sunroof", "Heated Seats", "Blind Spot Monitoring", "Wireless Charging"],
  },
  {
    id: "hyundai-sonata-1",
    name: "Hyundai Sonata",
    category: "sedan",
    images: [
      "/placeholder.svg?width=800&height=600&text=Hyundai+Sonata",
      "/placeholder.svg?width=800&height=600&text=Sonata+Interior",
      "/placeholder.svg?width=800&height=600&text=Sonata+Technology",
    ],
    seats: 5,
    engine: "2.5L Petrol",
    pricePerDay: 50,
    description: "Modern sedan with advanced safety features.",
    features: ["Lane Keep Assist", "Smart Cruise Control", "Wireless Charging", "Premium Audio"],
  },
  {
    id: "kia-picanto-1",
    name: "Kia Picanto",
    category: "compact",
    images: [
      "/placeholder.svg?width=800&height=600&text=Kia+Picanto",
      "/placeholder.svg?width=800&height=600&text=Picanto+Interior",
      "/placeholder.svg?width=800&height=600&text=Picanto+City",
    ],
    seats: 4,
    engine: "1.0L Petrol",
    pricePerDay: 35,
    description: "Economical and agile city car.",
    features: ["Air Conditioning", "USB Port", "Compact Size", "Easy Parking", "Fuel Efficient"],
  },
]
